// <auto-generated />
using System;
using Kalendr.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
#nullable disable
namespace Kalendr.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("Kalendr.API.Models.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<string>("Color")
                        .HasColumnType("text");
                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");
                    b.Property<string>("Description")
                        .HasColumnType("text");
                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");
                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");
                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");
                    b.Property<bool>("IsWorkHours")
                        .HasColumnType("boolean");
                    b.Property<Guid?>("RecurrenceId")
                        .HasColumnType("uuid");
                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("CreatedByUserId");
                    b.HasIndex("GroupId");
                    b.HasIndex("UserId");
                    b.ToTable("Events");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("EventId");
                    b.HasIndex("UserId");
                    b.ToTable("Comments");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventGroupShare", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");
                    b.HasKey("EventId", "GroupId");
                    b.HasIndex("GroupId");
                    b.ToTable("EventGroupShares");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("EventId");
                    b.HasIndex("UserId");
                    b.ToTable("Reactions");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventRsvp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");
                    b.Property<int>("Status")
                        .HasColumnType("integer");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.HasIndex("EventId", "UserId")
                        .IsUnique();
                    b.ToTable("Rsvps");
                });
            modelBuilder.Entity("Kalendr.API.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Groups");
                });
            modelBuilder.Entity("Kalendr.API.Models.GroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");
                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");
                    b.HasKey("GroupId", "UserId");
                    b.HasIndex("UserId");
                    b.ToTable("GroupMembers");
                });
            modelBuilder.Entity("Kalendr.API.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");
                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");
                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");
                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("Notifications");
                });
            modelBuilder.Entity("Kalendr.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");
                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("text");
                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("timestamp without time zone");
                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Email")
                        .IsUnique();
                    b.HasIndex("Username")
                        .IsUnique();
                    b.ToTable("Users");
                });
            modelBuilder.Entity("Kalendr.API.Models.CalendarEvent", b =>
                {
                    b.HasOne("Kalendr.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Kalendr.API.Models.Group", "Group")
                        .WithMany("Events")
                        .HasForeignKey("GroupId");
                    b.HasOne("Kalendr.API.Models.User", null)
                        .WithMany("Events")
                        .HasForeignKey("UserId");
                    b.Navigation("CreatedBy");
                    b.Navigation("Group");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventComment", b =>
                {
                    b.HasOne("Kalendr.API.Models.CalendarEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Kalendr.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Event");
                    b.Navigation("User");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventGroupShare", b =>
                {
                    b.HasOne("Kalendr.API.Models.CalendarEvent", "Event")
                        .WithMany("SharedWith")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Kalendr.API.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Event");
                    b.Navigation("Group");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventReaction", b =>
                {
                    b.HasOne("Kalendr.API.Models.CalendarEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Kalendr.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Event");
                    b.Navigation("User");
                });
            modelBuilder.Entity("Kalendr.API.Models.EventRsvp", b =>
                {
                    b.HasOne("Kalendr.API.Models.CalendarEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Kalendr.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Event");
                    b.Navigation("User");
                });
            modelBuilder.Entity("Kalendr.API.Models.GroupMember", b =>
                {
                    b.HasOne("Kalendr.API.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Kalendr.API.Models.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Group");
                    b.Navigation("User");
                });
            modelBuilder.Entity("Kalendr.API.Models.Notification", b =>
                {
                    b.HasOne("Kalendr.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });
            modelBuilder.Entity("Kalendr.API.Models.CalendarEvent", b =>
                {
                    b.Navigation("SharedWith");
                });
            modelBuilder.Entity("Kalendr.API.Models.Group", b =>
                {
                    b.Navigation("Events");
                    b.Navigation("Members");
                });
            modelBuilder.Entity("Kalendr.API.Models.User", b =>
                {
                    b.Navigation("Events");
                    b.Navigation("GroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
